### ISSUE TITLE
Parent Fight 

### ISSUE THREAD

**Issue by Parentfight** [GoogleCloudPlatform/terraform-google-three-tier-web-app#133]
Just a single mother and early childhood education  professional who for so long believe I was good at both.
Experienceing some hard knocks in the past 15 years has brought me to the belief that as long as I do my best all I can do is deal with the rest. 
This blog will share knowledge and possible suggestions of things I have learned or am learning. Helping in what ever way I can bring fulfillment and meaning to my life. So I pray that whatever I fill lead to share about will help you and you family in some way. We as parents really are in a fight for our children. To provide, teach, guide, give; what ever possible to enable our children to succeed it life.

**Comment by NimJay** [comment]
Seems like a bot.
