### ISSUE TITLE
The variable.tf file contains a typo:

### ISSUE THREAD

**Issue by nsoleimani** [GoogleCloudPlatform/terraform-google-three-tier-web-app#31]
https://github.com/GoogleCloudPlatform/terraform-google-three-tier-web-app/blob/7ba636ec067aa615c381a09b8f022ec8503655c2/variables.tf

The variable.tf file contains a typo:

variable "zone" { type = string description = "The Compute **Zonbe** to deploy to" }

**Comment by kumar-dhanagopal** [comment]
Fixed by #19 in the main branch. 

@nsoleimani - An internal action is pending to update the repo link in the console. I'll share more about that offline.
