### ISSUE TITLE
Would you enhance the application code running in Cloud Run?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/terraform-google-three-tier-web-app#53]
In README.md, I couldn't figure out what programming language or source code of the application running on Cloud Run (both frontend and API layer).

I think this `fe_image  = "gcr.io/sic-container-repo/todo-fe"` is related.

Would you enhance the README about how they are implemented?

**Comment by cklanac** [comment]
I had the same question... I wanted to see the source code for the application along with this tutorial. I realize the demo app is simple, but It would help me put the puzzle pieces together.

That said, a little GitHub searching returned [deploystack-three-tier-app](https://github.com/GoogleCloudPlatform/deploystack-three-tier-app), which I believe is the source code for the to-do app used in this demo.

https://github.com/GoogleCloudPlatform/deploystack-three-tier-app

**Comment by arizonal2014** [comment]
> I had the same question... I wanted to see the source code for the application along with this tutorial. I realize the demo app is simple, but It would help me put the puzzle pieces together.
> 
> That said, a little GitHub searching returned [deploystack-three-tier-app](https://github.com/GoogleCloudPlatform/deploystack-three-tier-app), which I believe is the source code for the ToDo app used in this demo.
> 
> Source: https://github.com/GoogleCloudPlatform/deploystack-three-tier-app Guide: https://cloud.google.com/shell/docs/cloud-shell-tutorials/deploystack/three-tier-app

Thanks. This is exactly what I was searching for.
