### ISSUE TITLE
Host

### ISSUE THREAD

**Issue by E-investment217** [GoogleCloudPlatform/terraform-google-three-tier-web-app#88]
"hosting"→Unexpected non-whitespace character after JSON←: {
  // ...

  // Applies a CORS header for all font files
  "headers": [ {
    "source": "**/*.@(eot|otf|ttf|ttc|woff|font.css)",
    "headers": [ {
      "key": "Access-Control-Allow-Origin",
      "value": "*"
    } ]
  } ]
}

Complete exception information is: Unexpected non-whitespace character after JSON at position 9 (line 1 column 10)

**Comment by donmccasland** [comment]
Deleting spam issue
